config/routes.rb
Rails.application.routes.draw do
  root 'rants#index'
    get '/sign-up' => 'registrations#new', as: :signup
    post '/sign-up' => 'registrations#create'

    get '/sign-in' => 'authentications#new', as: :signin
    post '/sign-in' => 'authentications#create'

    delete '/sign-out' => 'registrations#destroy', as: :signout

    get '/search' => 'rants#index', as: :search

    resources :users
    resources :rants
end

app/models/rant.rb
class Rant < ActiveRecord::Base

  belongs_to :user
  validates_length_of :body, minimum: 144, :allow_blank => false #wont allow blank
  validates :body, presence: :true
  validates :title, presence: :true

  def self.search(search)
    where("body ILIKE ? or title ILIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :rants

  def full_name
    "#{first_name} #{last_name}"
  end
  include Gravtastic
  gravtastic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by(id: session[:user_id])
  end

  helper_method :current_user

  def full_name
    
  end

end

app/controllers/rants_controller.rb
class RantsController < ApplicationController
  def index
    @rants = Rant.search(params[:search])
    if @rants.count < 1
      flash.now[:notice] = "These aren't droids you were looking for"
      render :index
    end
  end

  def new
    @rant = Rant.new
  end

  def create
    @rant = Rant.new(rant_params)
    @rant.user_id = current_user.id
    if @rant.save
      redirect_to rants_path, notice: "Rant Successfully Created!"
    else
      render :new
    end
  end

  def edit
    @rant = Rant.find(params[:id])
  end

  private

  def rant_params
    params.require(:rant).permit(:title, :body, :user_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Thanks for signing up"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rantly</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:400,900|Laila:700|Hind' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>

<body>


  <div class="navbar">
     <div class="container">
         <%= link_to "Rantly", root_path %>
         <span><%= link_to "Rants", root_path %></span>
         <span><%= link_to "Users", users_path %></span>
         <span><%= link_to "Styleguide", new_rant_path %></span>
         <% if current_user %>
            <span class="pull-right"><%= current_user.full_name %></span>
            <% else %>
            <span class="pull-right"><%= link_to "Sign Up", signup_path, class: "signup"  %></span>

         <% end %>
       </div>
     </div>

     <div class="search-header">
       <div class="container">
           <%= form_tag search_path, class:"search", :method => 'get' do %>
               <% if params[:search] == "" %>
                 <%= text_field_tag :search, params[:search], placeholder: "This can't be blank!", class: "search" %>
               <% else %>
                  <%= text_field_tag :search, params[:search], placeholder: "Search", class: "search" %>
               <% end %>
               <% end %>
             <%= link_to "New Rant", new_rant_path, class: "new-button" %>

         </div>
       </div>

    <div class="container">
      <div class="login-frame">
        <% if current_user == nil %>
          <br>
          <%= form_tag signin_path do  %>

          <div class = "has-feedback">
            <%= email_field_tag :email, nil, class:"user-form", placeholder: "Your email" %>
            <i class="fa fa-user form-control-feedback"></i>
          </div>

          <div class = "has-feedback">
            <%= password_field_tag :password, nil, class:"user-form", placeholder: "Your password" %>
            <i class="fa fa-lock form-control-feedback"></i>
          </div><br>
              <div>
                <%= submit_tag "Log In", class: "profile-button" %>
              </div>
              <div class="side-notice">
                <% if notice.is_a? String %>

                <%= notice %>

            <% end %>
              </div>


            <% end %>
            <% else %>
            <div class="picture" style="background-image: url('<%= current_user.gravatar_url %>')">
              </div>
              <br>
              <%= link_to "Log Out", signout_path, method: :delete, class: "profile-button drop"  %>
              <%= yield :side_error %>

            <% end %>



      </div>

      <div class="sub-container">
        <% if notice.is_a? String %>

        <%= notice %>

    <% end %>

          <span class="scroll"><%= yield %></span>
      </div>
     </div>

</body>

</html>

app/views/rants/edit.html.erb
<%  if @rant.errors.any? %>
  <% @rant.errors.full_messages.each do |message| %>
  <%= message %>
 <%  end %>

<% end %>

<div class="rant-frame">
 <%= form_for @rant do |f| %>
  <div class="rant-header">
    <h2><%= f.text_field :title, class: "wide" %></h2>
    <%= link_to "Delete", rant_path(@rant), method: :delete, class: "delete-button fa fa-trash-o" %>
    <%= link_to "Cancel", rants_path, class: "cancel-button fa fa-sign-in" %>
    <%= f.submit "Save", class: "body-button fa fa-upload lift" %>
  </div>


  <div class="rant-content">
    <div class="avatar">
      <div class="count-chocula">
        <span class ="countdown"></span>
      </div>
    </div>
      <%= f.text_area :body, class:"text-area message" %>
    </div>
 <% end %>

app/views/rants/index.html.erb
<div class="scroll">
  <% if @rants.count > 0 %>
      <% @rants.reverse_each do |rant| %>
      <div class="rant-frame">
        <div class="rant-header">
          <% if current_user && current_user.id == rant.user_id %>
            <%= link_to "Edit", edit_rant_path(rant), class: "body-button fa fa-edit" %>
          <% end %>
         <h2><%= rant.title %></h2><br>
</div>



               <div class="avatar">
               </div>

               <div class ="rant-content">
                 <%= rant.body %>
               </div>
             </div>

           <% end %>
             <% else %>

             <div class ="rant-frame">
               <center>
               <h2> These aren't the droids you are looking for.</h2>
               <h5>Keep Searching</h5>
             </center>
             </div>
           </div>

<% end %>

app/views/rants/new.html.erb
<% if @rant.errors.any? %>
  <% @rant.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<div class="rant-frame">
  <%= form_for @rant do |f| %>
    <div class="rant-header">
      <%= link_to " Cancel", root_path, class:"cancel-button fa fa-sign-in" %>
      <button class="body-button fa fa-upload lift"> Save</button>

      <h2><%= f.text_field :title, class: "wide", :placeholder => "Rant Title"  %></h2>


    </div>

    <div class="rant-content">
<div class="avatar">
</div>





     <%= f.text_area :body, class: "text-area message", :placeholder => "Start ranting" %>
<br><br><br><br><br><br><br><br><br><br><br>
     <span class ="countdown"></span>


  <% end %>
</div>
</div>

app/views/regristrations/new.html.erb
test